import { Metadata } from "next";
import { CONFIG } from "src/app/global-config";
import { LoginView } from "src/sections/auth/login/view";

// ------------------------------------------------------------

export const metadata: Metadata = {
  title: `Login - ${CONFIG.appName}`,
  description: "Generated by create next app",
};

// ------------------------------------------------------------

export default function Page() {
  return <LoginView />;
}
