import { Metadata } from "next";
import { CONFIG } from "src/app/global-config";
import { TemplateListView } from "src/sections/template/view";

// ------------------------------------------------------------

export const metadata: Metadata = {
  title: `Template | Dashboard - ${CONFIG.appName}`,
  description: "Generated by create next app",
};

// ------------------------------------------------------------

export default function Page() {
  return <TemplateListView />;
}
