import { Metadata } from "next";
import { CONFIG } from "src/app/global-config";
import { AccountView } from "src/sections/account/view";

// ------------------------------------------------------------

export const metadata: Metadata = {
  title: `Akun | Dashboard - ${CONFIG.appName}`,
  description: "Generated by create next app",
};

// ------------------------------------------------------------

export default function Page() {
  return <AccountView />;
}
