import { Metadata } from "next";
import { CONFIG } from "src/app/global-config";
import { InvoiceListView } from "src/sections/invoice/view";

// ------------------------------------------------------------

export const metadata: Metadata = {
  title: `Invoice | Dashboard - ${CONFIG.appName}`,
  description: "Generated by create next app",
};

// ------------------------------------------------------------

export default function Page() {
  return <InvoiceListView />;
}
