import { Metadata } from "next";
import { CONFIG } from "src/app/global-config";
import { CreditHistoryView } from "src/sections/credit/view/credit-history-view";

// ------------------------------------------------------------

export const metadata: Metadata = {
  title: `Riwayat Credit | Dashboard - ${CONFIG.appName}`,
  description: "Generated by create next app",
};

// ------------------------------------------------------------

export default function Page() {
  return <CreditHistoryView />;
}
