import { Metadata } from "next";
import { CONFIG } from "src/app/global-config";
import { CreditView } from "src/sections/credit/view";

// ------------------------------------------------------------

export const metadata: Metadata = {
  title: `Credit | Dashboard - ${CONFIG.appName}`,
  description: "Generated by create next app",
};

// ------------------------------------------------------------

export default function Page() {
  return <CreditView />;
}
