import { Metadata } from "next";
import { CONFIG } from "src/app/global-config";

// ------------------------------------------------------------------

export const metadata: Metadata = {
  title: `Not Found - ${CONFIG.appName}`,
  description: "Generated by create next app",
};

// ------------------------------------------------------------------

export default function Page() {
  return <div>Tidak ada apa-apa</div>;
}
