import { Metadata } from "next";
import { CONFIG } from "src/app/global-config";
import { DashboardView } from "src/sections/dashboard/view";

// ------------------------------------------------------------

export const metadata: Metadata = {
  title: `Dashboard - ${CONFIG.appName}`,
  description: "Generated by create next app",
};

// ------------------------------------------------------------

export default function Page() {
  return <DashboardView />;
}
